"""Generate stable StS2 model identities from the original design sheets."""
import json, pathlib, re
repo = pathlib.Path(__file__).resolve().parents[1]
def rows(name):
    return json.loads((repo / 'sheets' / (name + '.json')).read_text(encoding='utf-8-sig'))
def checked_ids(values):
    ids = list(values)
    if len(ids) != len(set(ids)) or any(not re.fullmatch(r'[a-z][a-z0-9_]*', key) for key in ids):
        raise ValueError('Model IDs must be unique, stable C# identifiers.')
    return ids
cards = checked_ids(r['id'] for r in rows('cards'))
powers = checked_ids([r['id'] for r in rows('power_effects')] + ['plated','reservoir','quiver','class'])
out = repo / 'sts2/Generated'
out.mkdir(parents=True, exist_ok=True)
(out / 'Cards.cs').write_text('// Generated by scripts/sts2-generate.py; stable saved-card identities.\nnamespace SpireLegacy;\n' + ''.join(f'public sealed class C_{key} : LegacyCard {{ public C_{key}() : base("{key}") {{ }} }}\n' for key in cards), encoding='utf-8')
(out / 'Powers.cs').write_text('// Generated by scripts/sts2-generate.py; native aliases are selected in LegacyPowers.\nnamespace SpireLegacy;\n' + ''.join(f'public sealed class P_{key} : LegacyPower {{ }}\n' for key in powers), encoding='utf-8')
for cls in ('knight','mage','ranger'):
    pool=[r for r in rows('card_pools') if r['classId']==cls]
    if len(pool)!=75: raise ValueError(f'{cls}: expected 75 cards, got {len(pool)}')
    if any(r['cardId'] not in cards for r in pool): raise ValueError(f'{cls}: unknown card')
print(f'Generated {len(cards)} cards and {len(powers)} power identities; 75 cards per class.')
